services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_INTERNAL_PORT}"
    command: redis-server --port ${REDIS_INTERNAL_PORT}
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - app_network
    # network_mode: "host"

  backend:
    #image: mika1512/pcap-catalog-service:2.5.0
    build: .                        
    container_name: backend
    restart: always
    depends_on:
      - redis
    ports:
      - "${BE_BASE_PORT}:${BE_INTERNAL_PORT}"
    volumes:
      - "${PCAP_DIRECTORIES}:${PCAP_MOUNTED_DIRECTORY}:ro"
    env_file:
      - .env
    networks:
      - app_network

  frontend:
    #image: mika1512/pcap-frontend-app:1.5.0
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:${NGINX_PORT}"
    env_file:
      - .env
    networks:
      - app_network

volumes:
  redis_data:
    # backend_logs:

networks:
  app_network:
    driver: bridge
